### ISSUE TITLE
Fails to install in Blender 3.6.1 (Linux)

### ISSUE THREAD

**Issue by castelblends** [takahirox/glTF-Blender-IO-EXT-mesh-gpu-instancing#15]
Hi,

I'm not able to install the addon in Blender 3.6.1 , do I have to install anything else?  (gltf2.0 exporter is enabled)

![scrsht](https://github.com/takahirox/glTF-Blender-IO-EXT-mesh-gpu-instancing/assets/61828683/c8dbb27a-22ce-4a43-8944-c4cfd8c811cd)

OS Ubuntu 23.04

Thanks.

**Comment by bendavis78** [comment]
I'm seeing this same issue:

```
Traceback (most recent call last):
  File "/usr/share/blender/3.6/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/.config/blender/3.6/scripts/addons/glTF-Blender-IO-EXT-mesh-gpu-instancing-0_0_3/__init__.py", line 4, in <module>
    from io_scene_gltf2.blender.exp import gltf2_blender_export_keys
ImportError: cannot import name 'gltf2_blender_export_keys' from 'io_scene_gltf2.blender.exp' (unknown location)

```
